### ISSUE TITLE
Text domain and theme slug is inconsistent throughout

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-pattern-library#102]
In different places, I'm seeing different text domains, mostly `theme_traditional`, `coherent`, and `component_s`.

I'm also seeing different theme slugs used to prefix php functions:

`add_image_size( 'thememodern-large' );`
`function theme_traditional_setup()`
`function component_s_jetpack_setup()`

Both text domain and theme slugs should be consistent across all files and types to avoid confusion and possible conflicts/errors.

Might be worth doing after #91, once we have a consistent naming strategy in place, since it will likely require manually sifting through each file.

**Comment by davidakennedy** [comment]
I'm going to take a pass through the files and make it `component_s ` for now. Having consistency here is crucial to getting the generator to work properly in Components – on these two enhancements:

https://github.com/Automattic/components.underscores.me/issues/5
https://github.com/Automattic/components.underscores.me/issues/32

**Comment by sarahmonster** [comment]
Would maybe just `components` work better? That way there aren't a lot of confusing underscores everywhere, and it's more consistent with how we've been referring to it elsewhere. (ie, we don't call it "Component _s", we call it "Components".)

**Comment by davidakennedy** [comment]
I'm cool with that. I'll run with it until someone changes my mind. :smile:

**Comment by karmatosed** [comment]
If we are calling it components that makes sense as a slug. But, we should remember we're allowing people to change their slug as they use the theme name.

**Comment by laurelfulford** [comment]
This should be fixed in the recent batch of merges.
