### ISSUE TITLE
Traditional Blog vs. Classic Blog

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/theme-pattern-library#119]
We refer to these interchangeably in the project. Can we pick one and stick with it?

My vote is for Classic Blog.

**Comment by sixhours** [comment]
I lean toward Classic Blog as well. It's Class-ier. ;)

**Comment by laurelfulford** [comment]
I prefer Classic as well.

**Comment by kathrynwp** [comment]
I vote Classic too. "Traditional" can carry negative connotations for some people.

**Comment by davidakennedy** [comment]
Old branch removed and renamed.
