### ISSUE TITLE
Gravatar hovers show generic Gravatar & name

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/theme-pattern-library#125]
When you hover over any Gravatar in the contributor section, the display name is "gravatarmysteryman" and the image is the grey-and-white default Gravatar.

**Expected:** when you hover over a Gravatar, it should display the user's name/username, bio (if available), and a smaller version of their Gravatar.

![underscores components custom starter themes for faster wordpress theme development](https://cloud.githubusercontent.com/assets/7662449/12625414/af0d4b86-c501-11e5-9237-c6ac7872a418.png)

**Comment by laurelfulford** [comment]
Yikes! It was not doing this locally :sob: 

I'm going to move this issue to the site repo: https://github.com/Automattic/components.underscores.me/
